let estado={b:0,q:0,resp:{},tiempo:0,total:0,conTiempo:true,custom:null}, intervalo=null;
const $=id=>document.getElementById(id), ABC='ABCD', HIST='efai_historial', ERR='efai_errores';
function bloques(){return estado.custom?[{key:'X',titulo:'Práctica de errores',minutos:20,preguntas:estado.custom}]:PREGUNTAS.bloques}
function iniciar(conTiempo,custom=null){estado={b:0,q:0,resp:{},tiempo:0,total:0,conTiempo,custom};$('inicio').classList.add('hide');$('resultados').classList.add('hide');$('examen').classList.remove('hide');cargarBloque()}
function cargarBloque(){clearInterval(intervalo);let b=bloques()[estado.b];estado.q=0;estado.tiempo=b.minutos*60;estado.total=estado.tiempo;$('titulo').textContent=b.titulo;mostrarPregunta();tick();if(estado.conTiempo)intervalo=setInterval(tick,1000)}
function svgFig(n,r=0){let p={star:'<polygon points="50,6 61,35 93,35 67,55 78,90 50,70 22,90 33,55 7,35 39,35"/>',arrow:'<path d="M12 55 L46 19 L46 40 L88 40 L88 70 L46 70 L46 91 Z"/>',circle:'<circle cx="50" cy="50" r="35"/>',diamond:'<polygon points="50,7 90,50 50,93 10,50"/>',cross:'<path d="M38 9H63V37H91V62H63V91H38V62H9V37H38Z"/>',moon:'<path d="M69 9C36 17 23 48 39 74C49 90 68 93 85 83C57 80 43 57 52 34C57 22 63 14 69 9Z"/>'}[n]||'<circle cx="50" cy="50" r="35"/>';return `<svg viewBox="0 0 100 100" style="transform:rotate(${r}deg)"><g fill="#d8dee9" stroke="#334155" stroke-width="3">${p}</g></svg>`}
function svgClock(h,m){let minAng=m*6, hourAng=((h%12)*30)+(m*0.5);let ticks='';for(let i=0;i<12;i++){let a=i*30*Math.PI/180,x1=60+44*Math.sin(a),y1=60-44*Math.cos(a),x2=60+49*Math.sin(a),y2=60-49*Math.cos(a);ticks+=`<line x1='${x1}' y1='${y1}' x2='${x2}' y2='${y2}'/>`}return `<svg viewBox='0 0 120 120'><circle cx='60' cy='60' r='52' fill='#fff' stroke='#334155' stroke-width='4'/><g stroke='#334155' stroke-width='3'>${ticks}</g><line x1='60' y1='60' x2='${60+28*Math.sin(hourAng*Math.PI/180)}' y2='${60-28*Math.cos(hourAng*Math.PI/180)}' stroke='#0f172a' stroke-width='6' stroke-linecap='round'/><line x1='60' y1='60' x2='${60+41*Math.sin(minAng*Math.PI/180)}' y2='${60-41*Math.cos(minAng*Math.PI/180)}' stroke='#0f766e' stroke-width='4' stroke-linecap='round'/><circle cx='60' cy='60' r='4' fill='#111'/></svg>`}
function mostrarPregunta(){let b=bloques()[estado.b], q=b.preguntas[estado.q];$('avance').textContent=`Pregunta ${estado.q+1}/${b.preguntas.length}`;let h=`<b>${q.id}</b><h2>${q.q}</h2>`;if(q.tipo==='fig'){h+=`<div class=modelo>${svgFig(q.fig,q.rot)}<div class=tapa></div></div><div class=figops>`;ABC.split('').forEach(L=>h+=`<div class="op ${estado.resp[q.id]===L?'sel':''}" onclick="elegir('${L}')"><b>${L}</b><br>${svgFig(q.op[L],q.rot)}</div>`);h+='</div>'}else if(q.tipo==='clock'){h+='<div class=clock-seq>';q.seq.forEach((c,i)=>h+=`<div class=clock-card>${svgClock(c.h,c.m)}<br><b>${i+1}</b></div>`);h+='<div class=clock-card><b>?</b></div></div><h3>Opciones</h3><div class=clock-options>';ABC.split('').forEach(L=>{let c=q.op[L];h+=`<div class="op clock-small ${estado.resp[q.id]===L?'sel':''}" onclick="elegir('${L}')"><b>${L}</b><br>${svgClock(c.h,c.m)}<br>${c.h}:${String(c.m).padStart(2,'0')}</div>`});h+='</div>'}else{ABC.split('').forEach(L=>h+=`<div class="op ${estado.resp[q.id]===L?'sel':''}" onclick="elegir('${L}')"><b>${L}</b> ${q.op[L]}</div>`)}h+=`<div class=acciones><button class=sec onclick=atras()>Atrás</button><button onclick=siguiente()>Siguiente</button></div>`;$('pregunta').innerHTML=h;scrollTo(0,0)}
function elegir(L){let q=bloques()[estado.b].preguntas[estado.q];estado.resp[q.id]=L;mostrarPregunta()}function atras(){if(estado.q>0){estado.q--;mostrarPregunta()}}function siguiente(){let b=bloques()[estado.b]; if(estado.q<b.preguntas.length-1){estado.q++;mostrarPregunta()}else terminarBloque()}
function tick(){if(!estado.conTiempo){$('timer').textContent='Libre';return}let m=Math.floor(estado.tiempo/60),s=estado.tiempo%60;$('timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('barra').style.width=(100*(1-estado.tiempo/estado.total))+'%';if(estado.tiempo<=0){terminarBloque();return}estado.tiempo--}
function terminarBloque(){clearInterval(intervalo);if(estado.b<bloques().length-1){$('examen').classList.add('hide');$('stop').classList.remove('hide')}else resultados()}
function siguienteBloque(){estado.b++;$('stop').classList.add('hide');$('examen').classList.remove('hide');cargarBloque()}
function textoOpcion(q,L){if(!q.op||!q.op[L])return '';let v=q.op[L];if(q.tipo==='clock')return `${v.h}:${String(v.m).padStart(2,'0')}`;return v}
function resultados(){clearInterval(intervalo);$('examen').classList.add('hide');let total=0,ok=0,fall=[],rev='',porBloque={};bloques().forEach(b=>{let c=0;b.preguntas.forEach(q=>{total++;let r=estado.resp[q.id]||'-',bien=r===q.r;if(bien){ok++;c++}else fall.push(q);rev+=`<div class=review><b>${q.id}</b> <span class=${bien?'ok':'bad'}>${bien?'Correcta':'Incorrecta'}</span><br>Pregunta: ${q.q}<br>Tu respuesta: ${r} ${textoOpcion(q,r)}<br>Correcta: ${q.r} ${textoOpcion(q,q.r)}<br>Explicación: ${q.exp}</div>`});porBloque[b.titulo]=`${c}/${b.preguntas.length}`});localStorage.setItem(ERR,JSON.stringify(fall));let pct=Math.round(ok/total*100);guardar(ok,total,pct);$('resultados').innerHTML=`<h2>Resultados</h2><div class=score>${ok}/${total}</div><p>${pct}%</p><h3>Por bloque</h3>${Object.entries(porBloque).map(x=>`<p><b>${x[0]}</b>: ${x[1]}</p>`).join('')}<button class=warn onclick=practicarErrores()>Practicar mis errores</button><details open><summary>Recrear respuestas</summary>${rev}</details><button onclick="location.reload()">Nuevo intento</button>`;$('resultados').classList.remove('hide');scrollTo(0,0)}
function practicarErrores(){let e=JSON.parse(localStorage.getItem(ERR)||'[]');if(!e.length){alert('No hay errores guardados todavía');return}iniciar(false,e)}function guardar(c,t,p){let h=JSON.parse(localStorage.getItem(HIST)||'[]');h.unshift({d:new Date().toLocaleString(),c,t,p});localStorage.setItem(HIST,JSON.stringify(h.slice(0,5)))}function historial(){let h=JSON.parse(localStorage.getItem(HIST)||'[]');if(h.length)$('historial').innerHTML='<h3>Últimos intentos</h3>'+h.map(x=>`<div class=review>${x.d}: <b>${x.c}/${x.t}</b> (${x.p}%)</div>`).join('')}historial();